---
home:
  startUri: "/home"
  paramUri: [ ]
  controller: App\Controller\Frontoffice\HomeController
  method: "index"
privacy:
  startUri: "/privacy"
  paramUri: [ ]
  controller: App\Controller\Frontoffice\HomeController
  method: "register"
articles:
  startUri: "/articles"
  paramUri: [ ]
  controller: App\Controller\Frontoffice\ArticleController
  method: "articles"
article:
  startUri: "/article"
  paramUri:
    - "slug"
  controller: App\Controller\Frontoffice\ArticleController
  method: "article"
login:
  startUri: "/login"
  paramUri: [ ]
  controller: App\Controller\Frontoffice\SecurityController
  method: "login"
logout:
  startUri: "/logout"
  paramUri: [ ]
  controller: App\Controller\Frontoffice\SecurityController
  method: "logout"
signin:
  startUri: "/signin"
  paramUri: [ ]
  controller: App\Controller\Frontoffice\SecurityController
  method: "register"
admin:
  startUri: "/admin"
  paramUri: [ ]
  controller: App\Controller\Backoffice\AdminArticleController
  method: "index"
admin_article_new:
  startUri: "/admin/article/new"
  paramUri: [ ]
  controller: App\Controller\Backoffice\AdminArticleController
  method: "new"
admin_article_edit:
  startUri: "/admin/article/edit"
  paramUri:
    - "slug"
  controller: App\Controller\Backoffice\AdminArticleController
  method: "edit"
admin_comments:
  startUri: "/admin/comments"
  paramUri: [ ]
  controller: App\Controller\Backoffice\AdminCommentController
  method: "comments"
admin_users:
  startUri: "/admin/users"
  paramUri: [ ]
  controller: App\Controller\Backoffice\AdminUserController
  method: "users"